---
- hosts: webservers

  tasks:
    - name: stop tomcat service
      ansible.builtin.service:
        name: tomcat
        state: stopped
    - name: uninstall tomcat
      ansible.builtin.yum:
        name: tomcat* 
        state: removed        
...